/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const eventParticipantsTable = {
    "name": "eventParticipants",
    "columns": {
        "userId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "eventId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "event_id"
        },
        "isBanned": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean,
            "serverName": "is_banned"
        },
        "bannedByUserId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "banned_by_user_id"
        },
        "bannedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "banned_at"
        },
        "mutedUntil": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "muted_until"
        },
        "mutedByUserId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "muted_by_user_id"
        },
        "customCooldownSeconds": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "custom_cooldown_seconds"
        },
        "role": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "user" | "admin"
        },
        "lastSeenAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "last_seen_at"
        },
        "currentPresence": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "offline" | "online" | "away",
            "serverName": "presence"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["userId", "eventId"],
    "serverName": "event_participants"
} as const;
const eventsTable = {
    "name": "events",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "codeName": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "code_name"
        },
        "description": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "name": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "isActive": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean,
            "serverName": "is_active"
        },
        "slowModeSeconds": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "slow_mode_seconds"
        }
    },
    "primaryKey": ["id"]
} as const;
const messagesTable = {
    "name": "messages",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "eventId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "event_id"
        },
        "userId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "text": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "replyToMessageId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "reply_to_message_id"
        },
        "isDeleted": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean,
            "serverName": "is_deleted"
        },
        "deletedByUserId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "deleted_by_user_id"
        },
        "deletedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "deleted_at"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const usersTable = {
    "name": "users",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "username": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "role": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as "user" | "admin"
        },
        "image": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "avatar_url"
        }
    },
    "primaryKey": ["id"]
} as const;
const eventParticipantsRelationships = {
    "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "users", "cardinality": "one" }],
    "event": [{ "sourceField": ["eventId"], "destField": ["id"], "destSchema": "events", "cardinality": "one" }],
    "mutedByAdmin": [{ "sourceField": ["mutedByUserId"], "destField": ["id"], "destSchema": "users", "cardinality": "one" }],
    "bannedByAdmin": [{ "sourceField": ["bannedByUserId"], "destField": ["id"], "destSchema": "users", "cardinality": "one" }]
} as const;
const eventsRelationships = {
    "messages": [{ "sourceField": ["id"], "destField": ["eventId"], "destSchema": "messages", "cardinality": "many" }],
    "participants": [{ "sourceField": ["id"], "destField": ["eventId"], "destSchema": "eventParticipants", "cardinality": "many" }]
} as const;
const messagesRelationships = {
    "event": [{ "sourceField": ["eventId"], "destField": ["id"], "destSchema": "events", "cardinality": "one" }],
    "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "users", "cardinality": "one" }],
    "parentMessage": [{ "sourceField": ["replyToMessageId"], "destField": ["id"], "destSchema": "messages", "cardinality": "one" }],
    "replies": [{ "sourceField": ["id"], "destField": ["replyToMessageId"], "destSchema": "messages", "cardinality": "many" }],
    "deletedBy": [{ "sourceField": ["deletedByUserId"], "destField": ["id"], "destSchema": "users", "cardinality": "one" }]
} as const;
const usersRelationships = {
    "messages": [{ "sourceField": ["id"], "destField": ["userId"], "destSchema": "messages", "cardinality": "many" }],
    "messagesDeletedBy": [{ "sourceField": ["id"], "destField": ["deletedByUserId"], "destSchema": "messages", "cardinality": "many" }],
    "eventParticipations": [{ "sourceField": ["id"], "destField": ["userId"], "destSchema": "eventParticipants", "cardinality": "many" }],
    "mutesGiven": [{ "sourceField": ["id"], "destField": ["mutedByUserId"], "destSchema": "eventParticipants", "cardinality": "many" }],
    "bansGiven": [{ "sourceField": ["id"], "destField": ["bannedByUserId"], "destSchema": "eventParticipants", "cardinality": "many" }]
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
    "tables": {
        "eventParticipants": eventParticipantsTable,
        "events": eventsTable,
        "messages": messagesTable,
        "users": usersTable
    },
    "relationships": {
        "eventParticipants": eventParticipantsRelationships,
        "events": eventsRelationships,
        "messages": messagesRelationships,
        "users": usersRelationships
    },
    "enableLegacyQueries": true,
    "enableLegacyMutators": true
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "eventParticipants" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type EventParticipant = Row<typeof eventParticipantsTable>;
/**
 * Represents a row from the "events" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Event = Row<typeof eventsTable>;
/**
 * Represents a row from the "messages" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Message = Row<typeof messagesTable>;
/**
 * Represents a row from the "users" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<typeof usersTable>;

/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = createBuilder(schema);
