/* eslint-disable */
/* tslint:disable */
// noinspection JSUnusedGlobalSymbols
// biome-ignore-all
/*
 * ------------------------------------------------------------
 * ## This file was automatically generated by drizzle-zero. ##
 * ## Any changes you make to this file will be overwritten. ##
 * ##                                                        ##
 * ## Additionally, you should also exclude this file from   ##
 * ## your linter and/or formatter to prevent it from being  ##
 * ## checked or modified.                                   ##
 * ##                                                        ##
 * ## SOURCE: https://github.com/0xcadams/drizzle-zero        ##
 * ------------------------------------------------------------
 */

import type { ZeroCustomType } from "drizzle-zero";
import type { default as zeroSchema } from "./drizzle-zero.config";

/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
    "tables": {
        "eventParticipants": {
            "name": "eventParticipants",
            "columns": {
                "userId": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "eventParticipants", "userId">,
                    "serverName": "user_id"
                },
                "eventId": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "eventParticipants", "eventId">,
                    "serverName": "event_id"
                },
                "isBanned": {
                    "type": "boolean",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "eventParticipants", "isBanned">,
                    "serverName": "is_banned"
                },
                "bannedByUserId": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "eventParticipants", "bannedByUserId">,
                    "serverName": "banned_by_user_id"
                },
                "bannedAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "eventParticipants", "bannedAt">,
                    "serverName": "banned_at"
                },
                "mutedUntil": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "eventParticipants", "mutedUntil">,
                    "serverName": "muted_until"
                },
                "mutedByUserId": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "eventParticipants", "mutedByUserId">,
                    "serverName": "muted_by_user_id"
                },
                "customCooldownSeconds": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "eventParticipants", "customCooldownSeconds">,
                    "serverName": "custom_cooldown_seconds"
                },
                "role": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "eventParticipants", "role">
                },
                "lastSeenAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "eventParticipants", "lastSeenAt">,
                    "serverName": "last_seen_at"
                },
                "currentPresence": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "eventParticipants", "currentPresence">,
                    "serverName": "presence"
                },
                "createdAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "eventParticipants", "createdAt">,
                    "serverName": "created_at"
                }
            },
            "primaryKey": ["userId", "eventId"],
            "serverName": "event_participants"
        },
        "events": {
            "name": "events",
            "columns": {
                "id": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "events", "id">
                },
                "codeName": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "events", "codeName">,
                    "serverName": "code_name"
                },
                "description": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "events", "description">
                },
                "name": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "events", "name">
                },
                "isActive": {
                    "type": "boolean",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "events", "isActive">,
                    "serverName": "is_active"
                },
                "slowModeSeconds": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "events", "slowModeSeconds">,
                    "serverName": "slow_mode_seconds"
                }
            },
            "primaryKey": ["id"]
        },
        "messages": {
            "name": "messages",
            "columns": {
                "id": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "messages", "id">
                },
                "eventId": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "messages", "eventId">,
                    "serverName": "event_id"
                },
                "userId": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "messages", "userId">,
                    "serverName": "user_id"
                },
                "text": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "messages", "text">
                },
                "replyToMessageId": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "messages", "replyToMessageId">,
                    "serverName": "reply_to_message_id"
                },
                "isDeleted": {
                    "type": "boolean",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "messages", "isDeleted">,
                    "serverName": "is_deleted"
                },
                "deletedByUserId": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "messages", "deletedByUserId">,
                    "serverName": "deleted_by_user_id"
                },
                "deletedAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "messages", "deletedAt">,
                    "serverName": "deleted_at"
                },
                "createdAt": {
                    "type": "number",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "messages", "createdAt">,
                    "serverName": "created_at"
                }
            },
            "primaryKey": ["id"]
        },
        "users": {
            "name": "users",
            "columns": {
                "id": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "users", "id">
                },
                "username": {
                    "type": "string",
                    "optional": false,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "users", "username">
                },
                "role": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "users", "role">
                },
                "image": {
                    "type": "string",
                    "optional": true,
                    "customType": null as unknown as ZeroCustomType<typeof zeroSchema, "users", "image">,
                    "serverName": "avatar_url"
                }
            },
            "primaryKey": ["id"]
        }
    },
    "relationships": {
        "eventParticipants": {
            "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "users", "cardinality": "one" }],
            "event": [{ "sourceField": ["eventId"], "destField": ["id"], "destSchema": "events", "cardinality": "one" }],
            "mutedByAdmin": [{ "sourceField": ["mutedByUserId"], "destField": ["id"], "destSchema": "users", "cardinality": "one" }],
            "bannedByAdmin": [{ "sourceField": ["bannedByUserId"], "destField": ["id"], "destSchema": "users", "cardinality": "one" }]
        },
        "events": {
            "messages": [{ "sourceField": ["id"], "destField": ["eventId"], "destSchema": "messages", "cardinality": "many" }],
            "participants": [{ "sourceField": ["id"], "destField": ["eventId"], "destSchema": "eventParticipants", "cardinality": "many" }]
        },
        "messages": {
            "event": [{ "sourceField": ["eventId"], "destField": ["id"], "destSchema": "events", "cardinality": "one" }],
            "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "users", "cardinality": "one" }],
            "parentMessage": [{ "sourceField": ["replyToMessageId"], "destField": ["id"], "destSchema": "messages", "cardinality": "one" }],
            "replies": [{ "sourceField": ["id"], "destField": ["replyToMessageId"], "destSchema": "messages", "cardinality": "many" }],
            "deletedBy": [{ "sourceField": ["deletedByUserId"], "destField": ["id"], "destSchema": "users", "cardinality": "one" }]
        },
        "users": {
            "messages": [{ "sourceField": ["id"], "destField": ["userId"], "destSchema": "messages", "cardinality": "many" }],
            "messagesDeletedBy": [{ "sourceField": ["id"], "destField": ["deletedByUserId"], "destSchema": "messages", "cardinality": "many" }],
            "eventParticipations": [{ "sourceField": ["id"], "destField": ["userId"], "destSchema": "eventParticipants", "cardinality": "many" }],
            "mutesGiven": [{ "sourceField": ["id"], "destField": ["mutedByUserId"], "destSchema": "eventParticipants", "cardinality": "many" }],
            "bansGiven": [{ "sourceField": ["id"], "destField": ["bannedByUserId"], "destSchema": "eventParticipants", "cardinality": "many" }]
        }
    }
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
